### ISSUE TITLE
Add fy-nl-ASR webservice  (frisian-dutch speech recognition)

### ISSUE THREAD

**Issue by proycon** [proycon/LaMachine#116]
With the resources downloadable from https://applejack.science.ru.nl/downloads/fame/fame/fame_resources.tar.gz (authentication required), this can now be added to LaMachine; in progress.

Users will need to set ``fame_user`` and ``fame_password`` in their LaMachine configuration.

(@vanlummelhuizen, @schemreier, @henkvdheuvel)

**Comment by proycon** [comment]
Ok, it all gets installed, took quite some more effort than envisioned, but something internal to fy_nl_ASR fails now:

```[CLAM Dispatcher] Adding to PYTHONPATH: /usr/local/lib/python3.5/dist-packages/fy_nl_ASR-0.1-py3.5.egg/fy_nl_ASR
[CLAM Dispatcher] Started CLAM Dispatcher v2.3.5 with fy_nl_ASR.fy_nl_ASR (2018-10-03 16:15:00)
[CLAM Dispatcher] Running /usr/local/lib/python3.5/dist-packages/fy_nl_ASR-0.1-py3.5.egg/fy_nl_ASR/fy_nl_ASR_wrapper.sh "/usr/local/var/www-data/fy_nl_ASR.clam/projects/anonymous/test/.status" "/usr/local/var/www-data/fy_nl_ASR.clam/projects/anonymous/test/input/" "/usr/local/var/www-data/fy_nl_ASR.clam/projects/anonymous/test/output/" "/usr/local/var/www-data/fy_nl_ASR.clam/scratch/" "/usr/local/lib/python3.5/dist-packages/fy_nl_ASR-0.1-py3.5.egg/fy_nl_ASR" "/usr/local/opt/fame_resources/"
[CLAM Dispatcher] Running with pid 177 (2018-10-03 16:15:00)
sox WARN rate: rate clipped 9670 samples; decrease volume?
sox WARN dither: dither clipped 8466 samples; decrease volume?
No squeue or qstat found, running local
Argument /usr/local/var/www-data/fy_nl_ASR.clam/scratch//bart.wav is a sound file, using it as audio
cat: /usr/local/var/www-data/fy_nl_ASR.clam/scratch//bart_18_10_03_16_10_00/intermediate/time.log: No such file or directory
cat: /usr/local/var/www-data/fy_nl_ASR.clam/scratch//bart_18_10_03_16_10_00/intermediate/data/ALL/segments: No such file or directory
Split 1 source file into 0 segment                              
cat: /usr/local/var/www-data/fy_nl_ASR.clam/scratch//bart_18_10_03_16_10_00/intermediate/data/ALL/spk2utt: No such file or directory
No speech found, exiting.
cp: cannot stat '/usr/local/var/www-data/fy_nl_ASR.clam/scratch//bart_18_10_03_16_10_00/bart_18_10_03_16_10_00.txt': No such file or directory
cp: cannot stat '/usr/local/var/www-data/fy_nl_ASR.clam/scratch//bart_18_10_03_16_10_00/bart_18_10_03_16_10_00.ctm': No such file or directory
cp: cannot stat '/usr/local/var/www-data/fy_nl_ASR.clam/scratch//bart_18_10_03_16_10_00/bart_18_10_03_16_10_00.rttm': No such file or directory
Traceback (most recent call last):
  File "./scripts/ctm2xml.py", line 22, in <module>
    f=codecs.open(ResFolder+'/'+UttId+'.ctm','r',encoding='utf-8')
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '/usr/local/var/www-data/fy_nl_ASR.clam/projects/anonymous/test/output//bart.ctm'
INFO       2018-10-03 16:15:00,815 Processing file '/usr/local/var/www-data/fy_nl_ASR.clam/projects/anonymous/test/output//bart.ctm'...
Traceback (most recent call last):
  File "./scripts/ctm2tg.py", line 100, in <module>
    main(sys.argv)
  File "./scripts/ctm2tg.py", line 39, in main
    word_tier_intervals = create_tier_intervals_from_ctm(os.path.join(ctm_file),textgrid_file)
  File "./scripts/ctm2tg.py", line 48, in create_tier_intervals_from_ctm
    ctm_file = open(path_to_ctm_file, "r")
IOError: [Errno 2] No such file or directory: '/usr/local/var/www-data/fy_nl_ASR.clam/projects/anonymous/test/output//bart.ctm'
/usr/local/var/www-data/fy_nl_ASR.clam/projects/anonymous/test
[CLAM Dispatcher] Process ended (2018-10-03 16:15:00, 0.35168s) 
[CLAM Dispatcher] Removing temporary files
[CLAM Dispatcher] Finished (2018-10-03 16:15:00), exit code 0, dispatcher wait time 0.35s, duration 0.352163s
```

**Comment by proycon** [comment]
Cross posted to schemreier/fy-nl_ASR#1 as it becomes an internal fy_nl_ASR issue.
