### ISSUE TITLE
lamachine update error in docker/VM: Syntax Error on call to ansible-playbook

### ISSUE THREAD

**Issue by proycon** [proycon/LaMachine#127]
Ansible fails with: 

```
Already up-to-date.
Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 67, in <module>
    import ansible.constants as C
  File "/usr/local/lib/python2.7/dist-packages/ansible/constants.py", line 17, in <module>
    from ansible.config.manager import ConfigManager, ensure_type, get_ini_config_value
  File "/usr/local/lib/python2.7/dist-packages/ansible/config/manager.py", line 16, in <module>                                                                                               
    from yaml import load as yaml_load
  File "/usr/local/lib/python-current/dist-packages/yaml/__init__.py", line 284
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid syntax
```

**Comment by proycon** [comment]
This is caused by the explicitly set PYTHONPATH in the global environment (which points to a python 3 installation, but ansible still uses python 2), unsetting PYTHONPATH solves it.
