### ISSUE TITLE
Problem on Arch Linux: installing common base packages fails

### ISSUE THREAD

**Issue by proycon** [proycon/LaMachine#161]
An issue in Ansible itself (ansible/ansible#63077) affects LaMachine on Arch:

```
TASK [lamachine-core : installing common base packages (Arch)] ************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
fatal: [mhysa.anaproy.nl]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/home/proycon/.ansible/tmp/ansible-tmp-1573819649.995037-121433623977085/AnsiballZ_pacman.py", line 102, in <module>
    _ansiballz_main()
  File "/home/proycon/.ansible/tmp/ansible-tmp-1573819649.995037-121433623977085/AnsiballZ_pacman.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/proycon/.ansible/tmp/ansible-tmp-1573819649.995037-121433623977085/AnsiballZ_pacman.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.packaging.os.pacman', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_pacman_payload_vA5yQB/ansible_pacman_payload.zip/ansible/modules/packaging/os/pacman.py", line 500, in <module>
  File "/tmp/ansible_pacman_payload_vA5yQB/ansible_pacman_payload.zip/ansible/modules/packaging/os/pacman.py", line 492, in main
  File "/tmp/ansible_pacman_payload_vA5yQB/ansible_pacman_payload.zip/ansible/modules/packaging/os/pacman.py", line 341, in install_packages
IndexError: list index out of range
```

The eventual solution (once it is fixed upstream) will be to update ansible yourself first, by doing a: ``pip install -U ansible``. For the time being it is broken though.

**Comment by proycon** [comment]
I managed to solve it in LaMachine instead.
