### ISSUE TITLE
Error when deploying virtual environment

### ISSUE THREAD

**Issue by faustusdotbe** [proycon/LaMachine#20]
This is what happens at step 3 of the [virtual environment method](https://proycon.github.io/LaMachine/), the bootstrapping part. It happens with and without `sudo`.

The log file does not show the error message, so I'm pasting the terminal output. 

```
sigmund@debian:~$ sudo /tmp/LaMachine/virtualenv-bootstrap.sh
(logging to /tmp/virtualenv-bootstrap-1487588652.log)
=====================================================================
           ,              LaMachine - NLP Software distribution
          ~)                     (https://proycon.github.io/LaMachine)
           (----í         Language Machines research group
            /| |\         & Centre for Language and Speech Technology
           / / /|	        Radboud University Nijmegen 
=====================================================================

Bootstrapping VirtualEnv....

================================================================================
      LaMachine will install the latest stable releases where possible
================================================================================
Detecting package manager...
Detected OS: debian
Detected distribution ID: debian
Detected distribution release: 8

-------------------------------
Updating global dependencies 
-------------------------------
 (this step, and only this step, may require root access, skip it with CTRL-C if you do not have it)
Command: sudo apt-get -m  install pkg-config git-core make gcc g++ autoconf automake autoconf-archive libtool autotools-dev libicu-dev libxml2-dev libxslt1-dev libbz2-dev zlib1g-dev libtar-dev libaspell-dev libhunspell-dev libboost-all-dev python3 python3-dev python3-pip python-virtualenv libgnutls28-dev libcurl4-gnutls-dev wget libexttextcat-dev libatlas-dev libblas-dev gfortran libsuitesparse-dev libfreetype6-dev myspell-nl perl libsort-naturally-perl tesseract-ocr tesseract-ocr-eng tesseract-ocr-nld poppler-utils
Ign http://ftp.belnet.be jessie InRelease
Hit http://ftp.belnet.be jessie-updates InRelease
(...)
Reading package lists...
Building dependency tree...
Reading state information...
libaspell-dev is already the newest version.
libatlas-dev is already the newest version.
autoconf is already the newest version.
autoconf-archive is already the newest version.
automake is already the newest version.
autotools-dev is already the newest version.
libblas-dev is already the newest version.
libboost-all-dev is already the newest version.
libbz2-dev is already the newest version.
libcurl4-gnutls-dev is already the newest version.
myspell-nl is already the newest version.
libfreetype6-dev is already the newest version.
g++ is already the newest version.
gcc is already the newest version.
gfortran is already the newest version.
git-core is already the newest version.
libgnutls28-dev is already the newest version.
libhunspell-dev is already the newest version.
libicu-dev is already the newest version.
libexttextcat-dev is already the newest version.
libsort-naturally-perl is already the newest version.
libtar-dev is already the newest version.
libtool is already the newest version.
libxml2-dev is already the newest version.
libxslt1-dev is already the newest version.
make is already the newest version.
perl is already the newest version.
pkg-config is already the newest version.
poppler-utils is already the newest version.
python3-pip is already the newest version.
python-virtualenv is already the newest version.
python3 is already the newest version.
python3-dev is already the newest version.
libsuitesparse-dev is already the newest version.
tesseract-ocr is already the newest version.
tesseract-ocr-eng is already the newest version.
tesseract-ocr-nld is already the newest version.
wget is already the newest version.
zlib1g-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.

-----------------------------------------
Creating virtual environment
-----------------------------------------
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 70, in <module>
    import packaging.version
ImportError: No module named 'packaging'
================ FATAL ERROR ==============
An error occurred during installation!!
Unable to create virtual environment
===========================================
```

`pip` and `pip3` are up to date, `packaging` exists in `pip` but throws an error in `pip3`:
```
sigmund@debian:~$ sudo pip install packaging
Requirement already satisfied: packaging in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages/six-1.10.0-py2.7.egg (from packaging)
Requirement already satisfied: pyparsing in /usr/lib/python2.7/dist-packages (from packaging)
sigmund@debian:~$ sudo pip3 install packaging
Traceback (most recent call last):
  File "/usr/bin/pip3", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 70, in <module>
    import packaging.version
ImportError: No module named 'packaging'
```

Passing the `python2` argument when bootstrapping the virtual environment throws the same error.

**Comment by proycon** [comment]
Hmm... can you do ``sudo apt-get install python3-virtualenv`` and try again?    If that doesn't work I suspect it may be a deeper problem with your distribution's pip3 installation, is it able to install any package at all?

By the way, do not use sudo for the entire bootstrap process, it will ask for sudo only for a two apt-get install commands, the rest should not be done as root.

**Comment by faustusdotbe** [comment]
`python3-virtualenv` was already installed and up to date, but it indeed seems my pip3 environment is broken (`ImportError: No module named 'packaging'` when installing another package).

Removing and reinstalling python3-pip doesn't seem to help.

Re-boostrapping with the latest commit produces the same error, unfortunately.

**Comment by proycon** [comment]
Okay, the latest fix indeed wouldn't help if your pip environment is broken. I wonder what caused the breakage in the first place. Do you have the packages ``python3-pkg-resources``  and ``python3-setuptools`` installed?  Did you ever install/upgrade pip manually outside of your package manager?

**Comment by faustusdotbe** [comment]
They're both installed and at the latest version. AFAIK I haven't installed
anything manually (or at least not Python-related).

Thanks

**Comment by proycon** [comment]
We'd have to debug a bit further to get to the bottom of why your pip is broken (it's not particularly LaMachine related anyhow). What do you get if you try the following? My output is from an up-to-date debian 9 system:

```
$ echo $PYTHONPATH

```

```
$ which python3
/usr/bin/python3
```

```
$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pip
>>> pip
<module 'pip' from '/usr/lib/python3/dist-packages/pip/__init__.py'>
>>> import packaging
>>> packaging
<module 'packaging' from '/usr/share/python-wheels/packaging-16.8-py2.py3-none-any.whl/packaging/__init__.py'>
>>> from pkg_resources import load_entry_point
```

**Comment by proycon** [comment]
I wonder if the latest fix by @rahiel resolves your issue?

**Comment by faustusdotbe** [comment]
It does! I also fixed my broken python environment (it turns out I did something wrong when installing anaconda).

Thanks for the help
