### ISSUE TITLE
Failure building labirinto on some machines

### ISSUE THREAD

**Issue by proycon** [proycon/LaMachine#209]
On some machines running an older version of openssl, LaMachine may fail with the following error when building *labirinto*:

```
Running: npm run build
- building for production...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/scratch/proycon/lmtest2/src/labirinto/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/scratch/proycon/lmtest2/src/labirinto/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/scratch/proycon/lmtest2/src/labirinto/node_modules/webpack/lib/NormalModule.js:471:10)
    at /scratch/proycon/lmtest2/src/labirinto/node_modules/webpack/lib/NormalModule.js:503:5
    at /scratch/proycon/lmtest2/src/labirinto/node_modules/webpack/lib/NormalModule.js:358:12
    at /scratch/proycon/lmtest2/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/scratch/proycon/lmtest2/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/scratch/proycon/lmtest2/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /scratch/proycon/lmtest2/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/scratch/proycon/lmtest2/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/scratch/proycon/lmtest2/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/scratch/proycon/lmtest2/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/scratch/proycon/lmtest2/src/labirinto/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /scratch/proycon/lmtest2/src/labirinto/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
```

This error was also reported [here](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported) and should be fixable by setting:

```
export NODE_OPTIONS=--openssl-legacy-provider
```

Do this prior to running ``lamachine-update`` or the initial lamachine bootstrap. I'm not hard-coding this in LaMachine as it's a security opt-out and updating your distribution and OpenSSL is always a preferred option.

Alternatively, you can simply not install the labirinto portal at all (if you don't need it and are only interested in the command-line interface that's the best option), just remove it from the installation manifest. Another last option is to configure lamachine to just ignore npm errors (``lamachine-config ignore_npm_errors yes`` prior to ``lamachine-update``).

**Comment by proycon** [comment]
(closing this issue as this is more an announcement for people encountering this and no further action is needed on our part)
