### ISSUE TITLE
Lamachine install on ponyland server leads to nodejs installation error

### ISSUE THREAD

**Issue by joostgrunwald** [proycon/LaMachine#215]
I tried to use the provided bash script to setup lamachine under /vol/tensusers4/grunwald at mistmane.sciece.ru.nl.
The build failed giving the following error:
https://exerror.com/opensslerrorstack-error03000086digital-envelope-routinesinitialization-error/

It seems to originate from the nodejs package, I tried to update with force=1 and force=2 but both would run into the same error.
Disabling node.js inside the lamachine setup does not solve the problem.

**Comment by joostgrunwald** [comment]
Running: npm run build
- building for production...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/webpack/lib/NormalModule.js:471:10)
    at /vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/webpack/lib/NormalModule.js:503:5
    at /vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/webpack/lib/NormalModule.js:358:12
    at /vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/webpack/lib/NormalModule.js:471:10)
    at /vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/webpack/lib/NormalModule.js:503:5
    at /vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/webpack/lib/NormalModule.js:358:12
    at /vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /vol/tensusers4/jgrunwald/my_lamachine/src/labirinto/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.7.0


MSG:

non-zero return code

**Comment by proycon** [comment]
Hmm.. nodejs seems notoriously prone to breakages. I'll have to investigate deeper. In the meantime I suggest you just remove "labirinto" and "nodejs" from the installation manifest. It's the portal website which you're probably not interested in anyhow.

**Comment by joostgrunwald** [comment]
I'm doing that at the moment. I'll update this post to show if this is a working temporary solution. I was running lamachine as a virtual environment with a stable release on a pony, mistmane to be precise. I did not have privileges, so I selected no there. I did not adjust the settings. I think that should be enough information to reproduce the problem. Would it be helpful to you if I shared my error log?

**Comment by joostgrunwald** [comment]
TASK [Installing configurable-http-proxy] **************************************

TASK [lamachine-run : Running npm install -g --prefix /vol/tensusers4/jgrunwald/my_lamachine configurable-http-proxy] ***
fatal: [mlp13.science.ru.nl]: FAILED! => {
    "changed": false,
    "cmd": "#!/bin/bash\nexport LM_QUIET=1\nif [ -e /home/jgrunwald/bin/lamachine-my_lamachine-activate ]; then\n    source /home/jgrunwald/bin/lamachine-my_lamachine-activate\nelse\n    echo \"Activation script /home/jgrunwald/bin/lamachine-my_lamachine-activate not found! \">&2\n    exit 2\nfi\nhash -r  #clear cache\necho \"Run environment:\">&2\necho \"    LM_NAME=$LM_NAME\">&2\necho \"    PATH=$PATH\">&2\necho \"    LD_LIBRARY_PATH=$LD_LIBRARY_PATH\">&2\necho \"    VIRTUAL_ENV=$VIRTUAL_ENV\">&2\necho \"    PYTHONPATH=$PYTHONPATH\">&2\necho \"    PYTHON=$(which python3)\">&2\necho \"    PIP=$(which pip3)\">&2\necho \"    LANG=$LANG\">&2\necho \"    LC_ALL=$LC_ALL\">&2\necho \"Running: npm install -g --prefix /vol/tensusers4/jgrunwald/my_lamachine configurable-http-proxy\">&2\nnpm install -g --prefix /vol/tensusers4/jgrunwald/my_lamachine configurable-http-proxy\n",
    "delta": "0:00:00.041007",
    "end": "2022-03-11 00:45:05.557119",
    "rc": 127,
    "start": "2022-03-11 00:45:05.516112"
}

STDERR:

Run environment:
    LM_NAME=my_lamachine
    PATH=/vol/tensusers4/jgrunwald/my_lamachine/bin:/home/jgrunwald/bin:/vol/tensusers4/jgrunwald/DISABLED/my_lamachine/bin:/home/jgrunwald/bin:/usr/local/slurm/bin:/usr/local/openmpi/bin:/usr/local/hwloc/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/cuda/bin:/usr/local/ponysay/bin:/opt/dell/srvadmin/bin
    LD_LIBRARY_PATH=/vol/tensusers4/jgrunwald/my_lamachine/lib/
    VIRTUAL_ENV=/vol/tensusers4/jgrunwald/my_lamachine
    PYTHONPATH=
    PYTHON=/vol/tensusers4/jgrunwald/my_lamachine/bin/python3
    PIP=/vol/tensusers4/jgrunwald/my_lamachine/bin/pip3
    LANG=en_US.UTF-8
    LC_ALL=en_US.UTF-8
Running: npm install -g --prefix /vol/tensusers4/jgrunwald/my_lamachine configurable-http-proxy
/bin/bash: line 20: npm: command not found


MSG:

non-zero return code

**Comment by proycon** [comment]
That error seems to stem from the Jupyter Hub installation. It indeed uses npm/nodejs to install a component but that dependency seems not to be properly declared, hence the error. Can you removed 'jupyter' (alongside 'labirinto' and 'nodejs') from the installation manifest and try again? You're probably not interested in an entire jupyter hub installation anyhow.

**Comment by joostgrunwald** [comment]
That fixed the problem :)

**Comment by proycon** [comment]
You're right, I was a bit premature and better keep it open
