### ISSUE TITLE
[lamachine2] Test other distributions

### ISSUE THREAD

**Issue by proycon** [proycon/LaMachine#41]
* Switch the base Linux distribution from Arch Linux to Debian Linux (stable/stretch), as this makes more sense in production environments (e.g wrt security) and is what more users     
  are accustomed too. (**DONE**)
* Allow for easy expansion to other distributions, allowing to accomodate production environments that run on e.g. CentOS.

**Comment by proycon** [comment]
Mostly implemented. Tests will still have to be conducted on other distributions.

**Comment by proycon** [comment]
CentOS7 currently fails on: 

```
Running: python3 -c 'import timbl'                                                                                                                                                                                                                            
Traceback (most recent call last):                                                                                                                                                                                                                            
  File "<string>", line 1, in <module>                                                                                                                                                                                                                        
  File "/usr/lib64/python3.4/site-packages/timbl.py", line 24, in <module>                                                
    import timblapi                                                                                                                                                                                                                                           
ImportError: /usr/lib64/python3.4/site-packages/timblapi.cpython-34m.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE   
```

**Comment by proycon** [comment]
Other distro tests now pass
