### ISSUE TITLE
mysqlclient error when starting t-scan

### ISSUE THREAD

**Issue by Duchadian** [proycon/LaMachine#71]
(lamachine-lm) duchs@duchsserver:webservice$ clamservice tscan
WARNING: No MySQL support available in your version of Python! pip install mysqlclient if you plan on using MySQL for authentication
Traceback (most recent call last):
  File "/home/duchs/lamachine-lm/bin/clamservice", line 11, in <module>
    sys.exit(main())
  File "/home/duchs/lamachine-lm/lib/python3.5/site-packages/clam/clamservice.py", line 2812, in main
    settings = importlib.import_module(settingsmodule)
  File "/home/duchs/lamachine-lm/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'tscan'

pip installing the mysqlclient resullts in an error code 1:

(lamachine-lm) duchs@duchsserver:webservice$ pip install mysqlclient
Collecting mysqlclient
  Downloading mysqlclient-1.3.12.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 1.6MB/s 
    Complete output from command python setup.py egg_info:
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5fszq8sz/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-build-5fszq8sz/mysqlclient/setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-build-5fszq8sz/mysqlclient/setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found

Though this seems to me like it could be a permission problem, though the same error occurs with sudo rights.

**Comment by proycon** [comment]
Ok, this is actually two issues. The mysql part if not really a problem, LaMachine doesn't ship a mysql server and t-scan should work fine without it. But the tscan import failing seems a LaMachine problem indeed.

**Comment by proycon** [comment]
Closing this, should be solved in tscan upon next release (hopefully)
